### ISSUE TITLE
Layout content is not showing after update 2.0.1 -> 2.0.4 (2.0.3)

### ISSUE THREAD

**Issue by kzotin** [androidx/constraintlayout#40]
Hi,

One of our layouts is not showing its content after updating ConstraintLayout to 2.0.4.

The code is quite complex, but I've succeeded to isolate the issue in the sample project:
https://github.com/kzotin/ConstraintBug

Before update: https://github.com/kzotin/ConstraintBug/blob/main/screen-2.0.1.jpg

After update: https://github.com/kzotin/ConstraintBug/blob/main/screen-2.0.4.jpg

Thanks in advance!

**Comment by wilburt** [comment]
Yeah, same here. Some layouts disappeared after 2.0.4 update

**Comment by PuppetZ** [comment]
yes, so do i

**Comment by camaelon** [comment]
This seems to be an issue with the optimizer, let me look into it.
I can get your view to work by setting optimizationLevel = 0 in KeyboardView.kt.

Note: a likely more optimized way would be to use match_parent instead of 0dp in item_keyboard.xml for the width.

**Comment by camaelon** [comment]
The issue might be caused by a bug in the ratio optimization. If instead of        app:layout_constraintDimensionRatio="h,1:1.3" you simply set it to   app:layout_constraintDimensionRatio="1.3:1" everything works. In this case, the "h,1:1.3" is also not super meaningful as the other dimension is a wrap_content, so only one side will use the ratio.

**Comment by camaelon** [comment]
Fixed in tip of tree.
