### ISSUE TITLE
Saving/Restoring Transition states

### ISSUE THREAD

**Issue by georgi-neykov-hub** [androidx/constraintlayout#41]
Hello,
I am using the latest stable version of the library (2.0.4) for implementing a complex layout  similar to the player/"up next" animations in YouTube Music with a `MotionLayout` as a root. I've setup the scene files for different configurations with scene files with 4 transitions, everything works like a charm, but I cannot manage to have the MotionLayout keep the screen state after orientation changes. It either does not pick the correct transition, or goes into meaningless [state A]->[state A] transitions. I've tried using `MotionLayout.getTransitionState`/`MotionLayout.setTransitionState()` as it seemed to store all needed data (start,end, progress, animation direction and speed).

I've searched through the documentation, went through videos from conferences but cannot seem to find more information on how to save restore state on the layout?

Is the `transitionState` property meant for the purpose, or we should be doing something else, or let individual view states be handled by the system? I care about having the same screen state after an configuration change (provided the states exist in both before/after configurations).

Thank you.

**Comment by jafu888** [comment]
MotionLayout does not automatically store the state for you (because of 2 below is common)

Three possibilities I can think of:
1. You are getting / setting at the wrong point. 
2. The "state" is more complex than the start state, end state, position, and velocity
3. MotionLayout has a bug

First make sure you are saving and restoring the state.
If you are doing a custom loading of the MotionScene / visibility of views etc. That must be set up.

3. Make a simple demo textView in (4 positions on the screen) that is not working for you and send it to us.

**Comment by georgi-neykov-hub** [comment]
Hello,
Thank you for the response. I've somewhat got through the problem for now by splitting the scene in nested `MotionLayout`s and playing with `progress` property.
I will close the issue.
