### ISSUE TITLE
how to use jumpToEnd tag in java code? 

### ISSUE THREAD

**Issue by aLLLiyyy** [androidx/constraintlayout#511]
I wanna implement the effect that transitionToEnd without animation when I first add a fragment to the viewpager2.
but I cannot find an regular api to support this method . when I use setProgress to 1.0F ,things seems okay for me, but I noticed a occurrence which is that I can not receive the onTransitionCompleted event when I add a transition listener to this motion layout,
then what can I do
thanks for reading

**Comment by aLLLiyyy** [comment]
@jafu888 thank you for your recommendation, I will find a better solution for my occasion.

**Comment by aLLLiyyy** [comment]
@jafu888  I came across a problem  which is I use glide to load gif into an imageview, the imageview is in a MotionLayout .
when I  manipulate the MotionLayout  with transitionToEnd but the GIF only show the first frame,it can not play the full gif.
Is it the reason because I manipulate the MotionLayout before fragment is resumed? how to solve the problem,thank you

**Comment by jafu888** [comment]
I am not familiar with how glide refreshes the image. 
I suspect it calls requestLayout() but libraries do all sort of strange things.

The requestLayout by default will get ignored during transitions because many Views response to being moved is to request layout. 
  You can test adding  `motion:layoutDuringTransition="honorRequest"`  to the Transition.
  There might also be options on Glide to make it work.

**Comment by aLLLiyyy** [comment]
@jafu888 i am so embarrassed because i made a mistake in manipulating the glide API.causing it only show the first frame! i have noticed the GIF playing mechanism which Is using a Handler to continuously receive drawing message and Draw to the imageview, requestLayout seems less affect the    glide GIF playing. anyway, thankyou for the powerful Motionlayout
