### ISSUE TITLE
Are there any comprehensive constraint set and various motion layout related docs for jetpack compose?

### ISSUE THREAD

**Issue by Debdutta-Panda** [androidx/constraintlayout#771]
There are no comprehensive docs on constraint layout and motion layout for jetpack compose of both json5 and programmatical approach. There are a few but they are outdated, and they may be written in 2021.

**Comment by jafu888** [comment]
Most up to date are in the [wiki](https://github.com/androidx/constraintlayout/wiki)
The intent is to evolve the documentation on this site and then transfer them to the inside google "official" documentation.

Most relevant:

ConstraintSet

- [Mapping from XML](https://github.com/androidx/constraintlayout/wiki/XML--to-JSON-and-DSL-for-ConstraintSet-attributes)
- [Examples](https://github.com/androidx/constraintlayout/tree/main/demoProjects/ExamplesComposeConstraintLayout) - WIP only one example

MotionLayout

- [Mapping from XML](https://github.com/androidx/constraintlayout/wiki/MotionLayout-XML-JSON-DSL-map)
- [General Syntax](https://github.com/androidx/constraintlayout/wiki/Compose-MotionLayout-JSON-Syntax)
- [Examples](https://github.com/androidx/constraintlayout/tree/main/demoProjects/ExamplesComposeMotionLayout) - WIP (5 examples)

If there are specific information you would like expanded on let us know.
It would help direct our documentation efforts

**Comment by Debdutta-Panda** [comment]
Thanks a lot for sharing the valuable links

**Comment by Debdutta-Panda** [comment]
The above shared links are ok, still I miss comprehensiveness in those. Here comprehensive means all the grammar of motion layout related json5 syntax, all possible dsl, method, scope, variables, etc. One place with all.

**Comment by jafu888** [comment]
We are in the middle of developing much of it motionLayout and documentation will improve over time.

[Mapping from XML](https://github.com/androidx/constraintlayout/wiki/MotionLayout-XML-JSON-DSL-map)
Is written from the perspective of someone that knows the XML. 
Currently we use that to track what has been done and what we have left.

For View it was embedded in the [Javadoc](https://developer.android.com/reference/androidx/constraintlayout/motion/widget/MotionLayout).
We will eventually extract the text from it and have something similar for JSON in the wiki.

The DSL will have regular Javadoc describing it.

We are still in the middle of writing the code and that will be our major focus for a while.

 If you are trying to understand the major concepts of MotionLayout look at the MotionTags Series on YouTube.
 [MotionTags](https://www.youtube.com/playlist?list=PLWz5rJ2EKKc-bcyUTIFAr97ZtRkwM7S4y)
 It is a series of short under 4 min videos covering all aspects motionLayout it is in video form because it is about animation.
 
 2 through 8 are still applicable. 
 
 1 View infrastructure, and we have no plans to implement 9 & 10

**Comment by Debdutta-Panda** [comment]
Ok, understood
